name: AWS Terraform Plan

on:
  workflow_call:
    inputs:
      gh_environment:
        description: 'GitHub deployment environment.'
        required: true
        type: string
    secrets:
      cli_config_credentials_token:
        description: 'Terraform Cloud API token.'
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.0
          cli_config_credentials_token: ${{ secrets.cli_config_credentials_token }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
