name: AWS Terraform Apply

on:
  workflow_call:
    inputs:
      gh_environment:
        description: 'GitHub deployment environment.'
        required: true
        type: string
    secrets:
      cli_config_credentials_token:
        description: 'Terraform Cloud API token.'
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    steps:
      - name: Trigger Terraform Apply
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.cli_config_credentials_token }}" \
            -H "Content-Type: application/vnd.api+json" \
            -d '{
                  "data": {
                    "type": "runs",
                    "attributes": {
                      "message": "Triggered apply via GitHub Actions"
                    }
                  }
                }' \
            https://app.terraform.io/api/v2/runs
