name: "EC2_Terraform"

on:
  workflow_dispatch:

jobs:
  Plan:
    uses: zetaaztra/aws_eks_labs/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: zetaaztra/aws_eks_labs/.github/workflows/aws_tf_apply.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
