name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to perform'
        required: true
        type: choice
        options:
          - Plan
          - Apply

jobs:
  plan:
    if: ${{ github.event.inputs.action == 'Plan' }}
    uses: ./.github/workflows/aws_tf_plan.yml
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  apply:
    if: ${{ github.event.inputs.action == 'Apply' }}
    needs: plan
    uses: ./.github/workflows/aws_tf_apply.yml
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
