name: "EC2_Terraform"

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  Plan:
    uses: zetaaztra/EC2_Terraform/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: zetaaztra/EC2_Terraform/.github/workflows/aws_tf_apply.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
